### PR TITLE
Add functionality for moodle mobile app

### PR DESCRIPTION
**Pull request by SnakyJake**

### CODE REVIEW

**Comment by PhilippImhof** [comment]
Thank you very much for that contribution. We are currently preparing a general overhaul in #35. As soon as this is done, we will gladly merge your PR. I have already tested it locally.

Do you think you have some time left to prepare a behat test or two? If you don't, that's not a problem. I will take care of it.

Also, we will try our best to react faster in the future.

**Comment by PhilippImhof** [comment]
Nevermind regarding behat tests, I have them (more or less) ready. Looking forward to integrating this soon.

**Comment by SnakyJake** [comment]
Hi Peter, I am sorry, but I have never done anything with behat tests and at the moment I don't have the time to read me into this.Best regardsJakobAm 04.10.2022 09:23 schrieb Philipp Imhof ***@***.***>:
Thank you very much for that contribution. We are currently preparing a general overhaul in #35. As soon as this is done, we will gladly merge your PR. I have already tested it locally.
Do you think you have some time left to prepare a behat test or two? If you don't, that's not a problem. I will take care of it.
Also, we will try our best to react faster in the future.

**Comment by PhilippImhof** [comment]
No worries at all. I have them ready.

**Comment by PhilippImhof** [comment]
This has now been integrated into PR #35 and will get merged into the main branch as soon as possible. Thanks again for your contribution.

**Pull request closed without merging**
