### PR TITLE
Refactor add/edit question form

### PR DESCRIPTION
**Pull request by PhilippImhof**
The add/edit question form contains some legacy code and does not follow current recommendations, e.g.
- form elements are injected via javascript, e.g. for the simplified grading criterion or the instantiation check; they do not integrate neatly
- form elements are hidden/shown via custom javascript instead of using the Form API's `hideIf()` function
- the instantiation check is done via XMLHttpRequest
- there is a global field for the unitpenalty and conversion rule, but the setting must be stored for each part; to achieve this, some javascript will copy the global value into hidden fields when saving the form or from the first part to the global field when the form is loaded
- there is a tweak in the code to "forward" a possible validation error from the first part's unitpenalty to the global field
- javascript code is ~10 years old and generates >300 linter errors and warnings

The three main consequences are:
- injecting elements instead of using the "official" way (Forms API) can lead to problems with certain themes, see e.g. [CONTRIB-7173](https://tracker.moodle.org/browse/CONTRIB-7173); it might also lead to problems with newer versions of Moodle
- using legacy javascript excludes the usage of newer features and might bring compatibility problems in the long run
- legacy code will always make it more difficult to move forward

I will therefore refactor this part of the code in order to:
- [x] use the Forms API wherever this is possible
- [x] remove "shadow" fields for unitpenalty and conversion rule, as they are only ever populated in the background
- [x] rewrite needed javascript as a module
- [x] rewrite the instantiation check as a Moodle web service and access it via the Moodle AJAX API
- [x] add behat testing, e.g. for the grading criterion settings and for the instantiation checks

~~In the long run~~, this will ~~probably~~ allow for quicker validation of the random/global and local variables fields *before* submission. 

TODO: 
- [x] Unit tests for the web service.

### CODE REVIEW

**Comment by PhilippImhof** [comment]
Just a little illustration for how the instantiation check and preview of data sets is working now.

Screenshot

**Comment by PhilippImhof** [comment]
On-the-fly validation of random variables, global variables and parts' local variables is ~~not completely~~ ready ~~yet~~. And there is some cleaning up to do.

**Comment by PhilippImhof** [comment]
Failing behat test seems to be a CI issue, there are no problems locally

**Comment by PhilippImhof** [comment]
This is now ready for review. Failing checks are a CI issue.

**Review by dbauer-ets — APPROVED** [review]
Hello Philipp,

I don't want to delay you any longer. I'll look at all that later when I have time. In the meantime, I approve the pull-request.

**Review by dbauer-ets — APPROVED** [review]

**Pull request merged**
