### PR TITLE
Extend poly() function

### LINKED ISSUE #21: Signs
Hello! 

Is it somehow possible to display the "+" sign on a positive number? I would like to set the following task:
variables:
m = {-4:4:0.1};
t = {-7:7:0.5};
Question text: ... $$ y = {m} ∗ x {t} $$ ...

If t is negative, there should be e.g. y = 4*x - 5, positive x = 4*x + 5.

Is that possible somehow? Many thanks for your help!

### PR DESCRIPTION
**Pull request by PhilippImhof**
As discussed in #21, the extended `poly()` function offers the following:
* full backwards compatibility
* formatting arbitrary linear combinations, optionally with a separator like `&` for LaTeX array or matrix environments
* usage with a single number in order to force the normally unnecessary `+` sign in front of the number

The functionality and syntax is best illustrated by some of its test cases:

* New functionality: formatting of a single number and forcing the `+` sign. While this is obviously not a polynomial, it is a useful "hack", because no one would use this function with just one number for any other purpose.
```
poly(5) => '+5'
poly(1.5) => '+1.5'
poly(0) => '0'
poly(-1.5) => '-1.5'
poly(-5) => '-5'
```

* New functionality: combining a single number with a variable (or arbitrary string) while optionally forcing the leading `+`. This syntax was not valid before, so no break in compatibility.
```
poly("x", -5) => '-5x'
poly("x", 3) => '3x'
poly("x", 1) => 'x'
poly("x", -1) => '-x'
poly("x", 3, "+") => '+3x'
poly("x^5", 3, "+") => '+3x^5'
```

* Default invocation prior to this change: one variable and a list of coefficients. Terms with a zero coefficient are not printed, the number 1 is not printed unless it forms the constant term. It is possible to use functions and other variables in the list of coefficients.
```
poly("x", [1, sqrt(3**2 1]) => 'x^{2}+3x+1'
poly("x", [1, 1, 1]) => 'x^{2}+x+1'
poly("y", [1, 0, 1]) => 'y^{2}+1'
poly("x", [1, 2, 3]) => 'x^{2}+2x+3'
poly("y", [-1, -2, -3]) => '-y^{2}-2y-3'
poly("y", [1, 1, 1]) => 'y^{2}+y+1'
# with previously defined variables a=5; b=2; 
p=poly([a,b]) => '5x+2'
# the following is discouraged, because the leading coefficient of a polynomial should not be zero
poly("x", [0, 0, 1]) => '1'
poly("y", [0, -1]) => '-1'
```

* new functionality: old syntax plus a separator:
```
poly("y", [2, -1], "&") => '2y&-1'
poly("z", [1, 1, 1], "&") => 'z^{2}&+z&+1'
poly("y", [-1, -2, -3], "&") => '-y^{2}&-2y&-3'
```

* new functionality: provide a list of strings and coefficients, plus an optional separator:
```
poly(["x", "y", "xy"], [-1, -2, -3]) => '-x-2y-3xy'
poly(["x", "y", "xy"], [1, 0, -3]) => 'x-3xy'
poly(["x", "y"], [1, 0, -3]) => 'x-3x'
poly(["x","y","z"], [1, 1, 1], "&") => 'x&+y&+z'
poly(["x","y","z"], [-2, -3, -4], "&") => '-2x&-3y&-4z'
poly(["x","y","z"], [-1, -1, -1], "&") => '-x&-y&-z'
poly(["x", "y"], [1, 1, 1, 1], "&") => 'x&+y&+x&+y'
# if the list of variables is shorter than the list of coefficients, we restart from the beginning
poly(["x", "y"], [1, 1, 1, 1]) => 'x+y+x+y'
```

* backwards compatibility: if called with just a list of coefficients, the default variable `x` is assumed:
```
poly([1, 1, 1]) => 'x^{2}+x+1'
poly([-1, -1, -1]) => '-x^{2}-x-1'
poly([1, 0, 1]) => 'x^{2}+1'
poly([1, 2, 3]) => 'x^{2}+2x+3'
poly([-1, -2, -3]) => '-x^{2}-2x-3'
poly([-1, -2, -3], "&") => '-x^{2}&-2x&-3'
# the following is discouraged, because the leading coefficient of a polynomial should not be zero
poly([0, 0, 1]) => '1'
poly([0, -1]) => '-1'
poly([0, 1], "&") => '&+1'
```

### CODE REVIEW

**Comment by dbauer-ets** [comment]
Hello Philipp,

Could you provide an example or two of the use of "&" for LaTeX array or matrix environments.

What is the maximum number of terms that a polynomial can have, three, ten, any number?

**Review by dbauer-ets — APPROVED** [review]
Hello Philipp,

Could you provide an example or two of the use of "&" for LaTeX array or matrix environments.

What is the maximum number of terms that a polynomial can have, three, ten, any number?

**Comment by PhilippImhof** [comment]
> Could you provide an example or two of the use of "&" for LaTeX array or matrix environments.

That actually made me think of yet another usage: formatting of matrix rows with no variables at all. So here we go with some examples:
```
p=poly("", [1, 1, 1, 1], "&") => '1&1&1&1'
p=poly("", [-1, 1, -1, 1], "&") => '-1&1&-1&1'
p=poly("", [1, -1, 1, -1], "&") => '1&-1&1&-1'
p=poly("", [0, 0, 0, 0], "&") => '0&0&0&0'
p=poly("", [1, 0, 2, 3], "&") => '1&0&2&3'
p=poly("", [0, 1, 0, -1], "&") => '0&1&0&-1'
```

> What is the maximum number of terms that a polynomial can have, three, ten, any number?

Technically, there is no hard limit, as variables and coefficients are just lists. However, I have not tested extremely large lists. I added a test case with 20 terms for the sake of illustration.

**Comment by dbauer-ets** [comment]
Hello Phillip,

I'm not sure about using the function to get an array. I know well that the coefficients of polynomials can become the elements of a matrix for example to solve a system of simultaneous equations, but wouldn't it be more appropriate to wait and process the vectors and matrices with new functions and keep polynomials to just do polynomials.

It also reminds me that polynomials are often used in equations with an = sign and a value on the other side of the equation. For example, it might be useful to be able to process the following equation with the poly() function:
2x^2 + 3x = 6
and why not
2x^2 + 3x = 6y^3
What do you think ?

**Comment by PhilippImhof** [comment]
> I'm not sure about using the function to get an array. 

I was using the term array only in reference to the LaTex `\begin{array}{...}...\end{array}` construct, so purely as a formatting thing.

>I know well that the coefficients of polynomials can become the elements of a matrix for example to solve a system of simultaneous equations, but wouldn't it be more appropriate to wait and process the vectors and matrices with new functions and keep polynomials to just do polynomials.

Currently, the parser only supports to kinds of lists: lists of numbers and lists of strings. It's virtually impossible to include matrices without rewriting that part of the code. That's one of my next projects, but it's a big one. 

The idea is: Formatting a polynomial, especially if one includes the `&` separator as someone proposed in the forum when requesting a function `lincomb()` (which is now not needed, because `poly()` can covert those use cases), follows more or less the same structure as formatting the row of a matrix. 

With the new syntax, it is possible to do e.g. the following:
```
# Random variables
r1=shuffle([5,3,8]);
r2=shuffle([2,4,1]);
r3=shuffle([-1,3,6]);
# Global variables
row1=poly("",r1,"&");
row2=poly("",r2,"&");
row3=poly("",r3,"&");
# Question text
\[ \begin{matrix}
{row1}\\
{row2}\\
{row3}
\end{matrix} \]
```
and get this:
Formatted matrix

> It also reminds me that polynomials are often used in equations with an = sign and a value on the other side of the equation. For example, it might be useful to be able to process the following equation with the poly() function: 2x^2 + 3x = 6 and why not 2x^2 + 3x = 6y^3 What do you think ?

That would be `\( {=poly([2,3,0])} = 6 \)` or `\( {=poly([2,3,0])} = 6y^3 \)` or even or `\( {=poly([2,3,0])} = {=poly("y",[6,0,0,0])} \)` with the coefficients probably coming from a random variable, as usage of `poly()` would only make sense if we need to account for different signs and coefficients being 1 or 0.

Having a function to render equations is not impossible, but not extremely useful IMHO, because the user would need to specify coefficients and variables for the left and right sign separately, plus the relation sign. So it would be something like `polyequation("x",[2,3,0],"y",[6,0,0,0],"=")`, but that is hardly less to type.

**Comment by dbauer-ets** [comment]
Granted. `\( {=poly([2,3,0])} = 6y^3 \)` or `\( {=poly([2,3,0])} = {=poly("y",[6,0,0,0])} \)` look o.k. to me.

```
row1=poly("",r1,"&");
row2=poly("",r2,"&");
row3=poly("",r3,"&");
\[ \begin{matrix}
{row1}\\
{row2}\\
{row3}
\end{matrix} \]
```
seems a bit cumbersome. I'm not sure it brings anything very useful or something that is urgently needed. It adds to the complexity of the function and, above all, it is doomed to become obsolete when we get matrix functions. I don't think it's a good approach to have the "&" part of the poly() function that we know for sure will be obsolete in the foreseeable future.

**Comment by dbauer-ets** [comment]
Eventually we'll have matrix functions and one that might look like this:

`A = matrix(r1,r2,r3);`

then `\[A\]` will display the matrix.

We are not yet there, but there is no emergency.

**Comment by PhilippImhof** [comment]
> It adds to the complexity of the function and

I see your point. IMHO it does not add much complexity once we have a formatter for polynomials (as we did before) or linear combinations with the option of including a LaTeX alignment separator (as was requested in the forum). It is just a nice application of the fact that one can provide an empty string as variable. There are basically two alternatives: either we do nothing about it and have `poly("", [1,2,3], "&") => ^{2}&+2&+3` following the principle "garbage in, garbage out", or we detect that invocation and print an error message. And the latter option is not much easier to code. (And now that it's done, it would be additional work to take it out, of course.)

> , above all, it is doomed to become obsolete when we get matrix functions. I don't think it's a good approach to have the "&" part of the poly() function that we know for sure will be obsolete in the foreseeable future.

The two are not related. The "&" in `poly()` can be useful e.g. for equation systems in an `{array}` environment (or whatever the person asking for that option in the forum had in mind; I will probably not use it myself, but I can imagine cases where it makes sense). For those not using it, it does no harm, they can just continue to use `poly()` without that optional parameter. Current users not reading the changelog will not even know that it exists. Matrices, once they are available, will not render that syntax obsolete, because they will only contain numbers. One could not use a matrix function to display a polynomial or linear combination. 

 Once we have matrix functionality, there's still two separate things: one is the matrix as a mathematical object, e.g. like `[[1,2],[3,4]]`, that we can store in a variable and that we can use in calculations, e.g. like `A=[[1,2],[3,4]]; d = det(A);` and the other is that we might then want to have a formatter like `formatmatrix(A)` (probably a nicer name) that would build a string suitable for inclusion in LaTeX / MathJax based on the matrix value itself. This is probably what you suggested in your second comment. (That function would need to have an optional parameter as well, because sometimes one needs the matrix in a `matrix` environments, but sometimes it's rather a `pmatrix`, `bmatrix` or `vmatrix`.

**Pull request merged**
